- name: Install the To-do app
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install git
      ansible.builtin.yum:
        name:
          - git
        state: present
      become: yes

    - name: Install python3
      ansible.builtin.yum:
        name: python3
        state: latest

    - name: Intall poetry
      ansible.builtin.shell:
        cmd:
          curl -sSL
          https://install.python-poetry.org |
          python3 -

    - name: Create Directory for To Do app
      ansible.builtin.file:
        path: /opt/todoapp
        owner: ec2-user
        state: directory
      become: yes

    - name:
        Get the latest version of the code from
        Git
      ansible.builtin.git:
        repo: https://github.com/talexandru1987/DevOps-Course-Starter.git
        dest: /opt/todoapp

    - name: Install project dependencies
      ansible.builtin.shell:
        cmd:
          cd /opt/todoapp;
          /home/ec2-user/.local/bin/poetry install
      become: yes

- name: Install .env from template
  hosts: webservers
  vars_prompt:
    - name: key
      prompt: "Enter the trello key"
      private: no

    - name: token
      prompt: "Enter the trello token"
      private: no
  tasks:
    - name: Copy .env file using template
      ansible.builtin.template:
        src: /home/ec2-user/.env.j2
        dest: /opt/todoapp/.env

    - name: Copy the service file
      ansible.builtin.copy:
        src: /home/ec2-user/todoapp.service
        dest: /etc/systemd/system/todoapp.service
      become: yes

    - name: start he To-do App
      ansible.builtin.systemd:
        name: todoapp.service
        daemon_reload: true
        state: "restarted"
      become: yes
