name: Continuous Integration
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    # Only on pull requests to main
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello Alexandru

      - name: build docker image
        run: docker build --target test --tag
          test-image .

      - name: run docker image
        run: docker run test-image

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        #continue even if vulnerabilities are found
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
