name: Continuous Integration
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Hello Alexandru

      - name: build docker image
        run: docker build --target test --tag
          test-image .

      - name: run docker image
        run: docker run test-image
